### PR TITLE
Vulkan docs v1.0.7

### PR DESCRIPTION
**Pull request by ParticlePeter**
Now the Generator works for vulkan-docs versions up to version v1.0.12
Additionally I grouped all the separated features and added platform surface specific code and imports. 
Those can be activated with the same enums as in vk_platform.h

A side note, I see that you are not interested much in my additions, but I would like to make them available to the community via dub. I'll create an own project, announce it and not that it based on your work, hope you have no issue with this. You will still be mentioned as author. If you don't comment on this I will proceed.

### CODE REVIEW

**Comment by Vild** [comment]
I would appreciate if you proceeded with making your own dub entry.
Your wrapper code seems to be the best one out there and it's a shame that it is not up on dub yet.

**Comment by ParticlePeter** [comment]
@Vild, just registered it, its called `erupted`. Next Sunday I will make the official announcement.

**Comment by ColonelThirtyTwo** [comment]
Apparently I was not watching my own repositories. I am sorry for not responding.

Please split up your commits. Several of your commits make multiple changes in a single commit (ex. changing formatting of template strings and a new feature) in a way that is hard to cherry-pick.

Note that GitHub pull requests track branches. You have 3 pull requests tracking the same branch.

For platform API support, I don't want to tie dvulkan to a specific set of bindings, which may become abandoned/old and are incompatible with any alternative bindings, when (AFAIK) the only thing the platform APIs need is a single opaque struct type for the window/surface/whatever. I'd much rather take a `void*` instead.

**Comment by ParticlePeter** [comment]
> Please split up your commits. Several of your commits make multiple changes in a single commit (ex. changing formatting of template strings and a new feature) in a way that is hard to cherry-pick.
> 
> Note that GitHub pull requests track branches. You have 3 pull requests tracking the same branch.

Yes, unfortunately I was working on two things interleaved and I can't split them up any more, lot of changes. Actually I did create several branches and send you the pull requests to them separately so that you could cherry pick them. Later on I merged them back into master, that might be the mess up, sorry.

> For platform API support, I don't want to tie dvulkan to a specific set of bindings, which may become abandoned/old and are incompatible with any alternative bindings, when (AFAIK) the only thing the platform APIs need is a single opaque struct type for the window/surface/whatever. I'd much rather take a void\* instead.

No bindings involved so far. The original idea was to create those module imports as stubs, and leave it to the user to supply them in the proper directory structure with source- and importPaths specified. 
But I think that with optional dependencies on dub bindings via configurations would be ok. If the binding vanishes, the configuration cannot be used anymore, and it should be task of the vulkan bindings maintainer and the community to resolve this problem.
By the way, you are wrong, there are some platform dependent functions which you have not exposed, additionally, when you use one opaque struct for all the cases where do you think the compiler could get all the different definitions from?

**Pull request closed without merging**
